# Generated by Django 3.1 on 2020-08-28 08:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200828_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bodys',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
