# Generated by Django 3.1 on 2020-08-27 05:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200824_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
