# Generated by Django 3.1 on 2020-08-28 08:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_project_bodys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bodys',
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
