# Generated by Django 3.1 on 2020-08-28 09:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20200828_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
