# Generated by Django 3.1 on 2020-08-30 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200821_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_login',
            field=models.DateField(default=datetime.datetime(2020, 8, 30, 2, 6, 47, 360435, tzinfo=utc)),
        ),
    ]
