# Generated by Django 3.1 on 2020-08-30 02:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_previous_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='previous_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 2, 14, 6, 217578, tzinfo=utc)),
        ),
    ]
